### ISSUE TITLE
Vignette won't knit

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/allodb#162]
The colours are improperly specified on line 102, https://github.com/forestgeo/allodb/blob/72465069e09a6cc47a8dcf27d8a6ed81dc1088bd/vignettes/allodb-vignette.Rmd#L101.

``` r
plot(
  x = scbi_stem1$dbh,
  y = scbi_stem1$agb,
  col = scbi_stem1$genus,
  xlab = "DBH (cm)",
  ylab = "AGB (kg)"
)
#> Error in plot(x = scbi_stem1$dbh, y = scbi_stem1$agb, col = scbi_stem1$genus, : object 'scbi_stem1' not found
```

<sup>Created on 2021-09-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by maurolepore** [comment]
Thanks! Should now be fixed by #167
