### ISSUE TITLE
website not updating

### ISSUE THREAD

**Issue by gonzalezeb** [ropensci/allodb#172]
If I understand correctly, the allodb website should be updating automatically as mentioned [here](https://devguide.ropensci.org/building.html?q=website#:~:text=You%20only%20need%20to%20worry%20about%20automatic%20deployment%20of%20your%20website%20until%20approval%20and%20transfer%20of%20your%20package%20repo%20to%20the%20ropensci%20organization%3B%20indeed%2C%20after%20that%20a%20pkgdown%20website%20will%20be%20built%20for%20your%20package%20after%20each%20push%20to%20the%20GitHub%20repo.). However, the website is not updating (nor the images are showing), is there anything I need to do?. What do you think @maurolepore?

**Comment by maurolepore** [comment]
I base this comment on the website I see at:
https://docs.ropensci.org/allodb

This seems indeed wrong:

x. I do note the images in README are corrupt (I see an
icon but not the image):
https://docs.ropensci.org/allodb/index.html#examples
-- I'll investigate.

These seems okay to me:

v. I note the images in the article seem ok to me:
https://docs.ropensci.org/allodb/articles/allodb-vignette.html

v. I see rOpenSci builds show an update for allodb in Oct 1,
which suggests the building process is fine:
https://ropensci.r-universe.dev/ui#builds

v. I see the website shows the badges as of the latest changes
I pushed, suggesting text is updating as expected. See the 3
badges "Peer Reviewed", "codecov", and "R-CMD-check" at:
https://docs.ropensci.org/allodb/

--

Erika, appart from the images in README, do you see any other
image that is corrupt, or any other text is not up to date?
Please share the link and maybe an sceenshot if that helps.

**Comment by gonzalezeb** [comment]
Thanks Mauro. Everything seems to be working fine.
