### ISSUE TITLE
Prune data-raw/

### ISSUE THREAD

**Issue by maurolepore** [ropensci/allodb#213]
At least one file in data-raw/ doesn't work. I suspect this
directory is stale and maybe it's a good time to prune it.

**Comment by gonzalezeb** [comment]
I guess you refer to [this file](https://github.com/ropensci/allodb/blob/master/data-raw/create_db.md) and it seems that it can be delete it (no longer valid). 

 I also think that [this other file](https://github.com/ropensci/allodb/blob/master/data-raw/create_reference_id.R) is not needed as a "reference_id" is taken from "[availble_ramdom_ids file](https://github.com/ropensci/allodb/blob/master/data-raw/available_random_ids.csv). 

Everything in the csv_database folder is used.
